import localFont from 'next/font/local';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import '~/styles/globals.css';
import dynamic from 'next/dynamic';

// IMPORTANT: disable SSR for client-only providers (wallet, indexedDB users)
const ClientRoot = dynamic(
  () => import('~/components/client-root').then((m) => ({ default: m.ClientRoot })),
  { ssr: false }
);

const pokerFont = localFont({
  src: '../../public/fonts/poker.otf',
  variable: '--font-poker',
});

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`font-sans ${GeistSans.variable} ${pokerFont.variable}`}>
        <ClientRoot>{children}</ClientRoot>
      </body>
    </html>
  );
}