import localFont from 'next/font/local';

import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import { Navbar } from '~/components';
import { Web3Provider } from '~/providers';
import '~/styles/globals.css';

import { Toaster } from '~/components/ui/sonner';
import { AgeVerificationModal } from '~/components/age-verification';

import { ThemeProvider } from '../providers/theme-provider';

const pokerFont = localFont({
  src: '../../public/fonts/poker.otf',
  variable: '--font-poker',
});

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={`font-sans ${GeistSans.variable} ${pokerFont.variable}`}>
        <ThemeProvider>
          <Web3Provider>
            <AgeVerificationModal />
            <Navbar />
            {children}
            <Toaster />
          </Web3Provider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
