[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
fs_permissions = [
    { access = "read-write", path = "../../" },
    { access = "read-write", path = "./" },
]
ffi = true

# Extreme size optimization for Lisk Sepolia deployment
# Use with: forge build --profile size-optimized
[profile.size-optimized]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 1  # Minimize deployed bytecode size
evm_version = "paris"  # Use latest stable EVM version
gas_reports = ["*"]
fs_permissions = [
    { access = "read-write", path = "../../" },
    { access = "read-write", path = "./" },
]
ffi = true


[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
hedera_testnet = "https://testnet.hashio.io/api"
hedera_mainnet = "https://mainnet.hashio.io/api"

[etherscan]
lisk_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://sepolia-blockscout.lisk.com/api" }
hedera_testnet = { key = "test", url = "https://server-verify.hashscan.io" }
hedera_mainnet = { key = "main", url = "https://server-verify.hashscan.io" }
